config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :posts do
    resources :comments, only: %i[create edit update destroy], module: 'posts'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, length: { maximum: 500 }
end

app/models/post/comment.rb
# frozen_string_literal: true

class Post::Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def index; end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @post, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.destroy
      redirect_to @post, notice: 'Comment was successfully deleted'
    else
      redirect_to @post
    end
  end

  private

  def comment_params
    params.require(:post_comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = Post.find params[:id]

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find params[:id]

    @post.destroy

    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/post_comments_helper.rb
# frozen_string_literal: true

module PostCommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/homes/index.html.slim
= content_for :title do
  = 'Home#index'

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title Nested resources
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              h2 = yield :title

            == yield

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav
          li.nav-item.me-2
            = link_to 'Home', root_path, class: 'nav-link link-dark'
          li.nav-item.me-2
            = link_to 'Posts', posts_path, class: 'nav-link link-dark'

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :title
  = f.input :body

  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

app/views/posts/comments/_form.html.slim
= simple_form_for @comment, url: url do |f|
  = f.input :body

  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

app/views/posts/comments/edit.html.slim
= content_for :title, 'Editing comment'
= render 'form', comment: @comment, url: post_comment_path(@post, @comment)

app/views/posts/edit.html.slim
= content_for :title do
  = 'Editing post'

== render 'form'

hr

.d-flex
  = link_to 'Show', @post, class: 'btn btn-outline-primary me-2'
  = link_to 'Back', :back, class: 'btn btn-outline-primary'

app/views/posts/index.html.slim
= content_for :title do
  = 'Posts'

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope: :col } #
      th{ scope: :col } Title
      th

  tbody
    - @posts.each_with_index do |post, i|
      tr
        th{ scope: :col } = i + 1
        td = post.title
        td.d-flex
          .me-4 = link_to 'Show', post
          .me-4 = link_to 'Edit', edit_post_path(post)
          = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

= link_to 'New Post', new_post_path, class: 'btn btn-primary'

app/views/posts/new.html.slim
= content_for :title do
  = 'New post'

== render 'form'

hr

= link_to 'Back', :back, class: 'btn btn-outline-primary'

app/views/posts/show.html.slim
- content_for :title do
  = @post.title
p
  strong.me-2 Body:
  = @post.body
.d-flex
  = link_to 'Edit', edit_post_path(@post), class: 'btn btn-outline-primary mr-2'
  = link_to 'Back', :back, class: 'btn btn-outline-primary'

hr

h2 = "Add new comments"
== render 'posts/comments/form', comment: @comment, url: post_comments_path(@post)
hr

h2 = "Comments list"
- @post.comments.each do |comment|
  - if comment.id.present?
    .card.mb-2.p-3
      .d-flex.justify-content-between.align-items-center
        .col-8
          small.font-weight-bold
            == comment.body
        .col-4
          = link_to 'Edit', edit_post_comment_path(@post, comment), class: 'btn btn-outline-primary mr-2'
          = link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary mr-2'